version: "3"
services:
#  postgres_customer-activity:
#    image: postgres:13
#    container_name: psql.customer-activity
#    ports:
#      - 5437:5432
#    environment:
#      POSTGRES_USER: customer-activity
#      POSTGRES_PASSWORD: customer-activity
#      POSTGRES_DB: customer-activity

  fpm_customer-activity:
    container_name: fpm.customer-activity
    image: ewwgenn/storytale:fpm7.4_LOCAL
    env_file: ./../../config/.env
    restart: always
    cap_add:
      - ALL
    volumes:
      - "./../../:/www/"

  nginx_customer-activity:
    container_name: nginx.customer-activity
    image: nginx:alpine
    restart: always
    depends_on:
      - fpm_customer-activity
    links:
      - fpm_customer-activity:fpm_customer-activity.local
    ports:
      - "7009:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"

  subscriber_customer-activity:
    container_name: subscriber.customer-activity
    build:
      context: ./
      dockerfile: subscriber/Dockerfile
    env_file: ./../../config/.env
    restart: always
    cap_add:
      - ALL
    volumes:
      - "./../../:/www/"

  cron_customer-activity:
    container_name: cron.customer-activity
    build:
      context: ./
      dockerfile: cron/Dockerfile
    env_file: ./../../config/.env
    restart: always
    cap_add:
      - ALL
    volumes:
      - "./../../:/www/"