version: "3.5"
services:
#  postgres_customer-activity:
#    image: postgres:13
#    container_name: psql.customer-activity
#    ports:
#      - 5437:5432
#    environment:
#      POSTGRES_USER: customer-activity
#      POSTGRES_PASSWORD: customer-activity
#      POSTGRES_DB: customer-activity

  fpm_customer-activity:
    container_name: fpm.customer-activity
    image: ewwgenn/fpm_with_auth7.4:1.03
    env_file: ./../../config/.env
    restart: always
    cap_add:
      - ALL
    volumes:
      - "./../../:/www/"
    networks: 
      - story_network  

  nginx_customer-activity:
    container_name: nginx.customer-activity
    image: nginx:alpine
    restart: always
    depends_on:
      - fpm_customer-activity
    links:
      - fpm_customer-activity:fpm_customer-activity.local
    ports:
      - "192.168.200.1:7009:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
    networks: 
      - story_network    

  subscriber_customer-activity:
    container_name: subscriber.customer-activity
    build:
      context: ./
      dockerfile: subscriber/Dockerfile
    env_file: ./../../config/.env
    restart: always
    cap_add:
      - ALL
    volumes:
      - "./../../:/www/"
    networks: 
      - story_network  

  cron_customer-activity:
    container_name: cron.customer-activity
    build:
      context: ./
      dockerfile: cron/Dockerfile
    env_file: ./../../config/.env
    restart: always
    cap_add:
      - ALL
    volumes:
      - "./../../:/www/"
    networks: 
      - story_network

networks:
  story_network:
    name: story_network          
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/26
