<?php

namespace RestAPI\Controller;

use Storytale\CustomerActivity\Application\Query\Customer\CustomerDataProvider;
use Zend\Mvc\Controller\AbstractRestfulController;

class CustomerController extends AbstractRestfulController
{
    /** @var CustomerDataProvider */
    private CustomerDataProvider $customerDataProvider;

    public function __construct(CustomerDataProvider $customerDataProvider)
    {
        $this->customerDataProvider = $customerDataProvider;
    }

    public function create($data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function get($id)
    {
        return parent::get($id); // TODO: Change the autogenerated stub
    }

    public function getList()
    {
        return parent::getList(); // TODO: Change the autogenerated stub
    }
}