<?php

namespace RestAPI\Controller;

use Storytale\CustomerActivity\Application\Query\Subscription\SubscriptionPlanDataProvider;
use Zend\Mvc\Controller\AbstractRestfulController;
use Zend\View\Model\JsonModel;

class SubscriptionPlanController extends AbstractRestfulController
{
    /** @var SubscriptionPlanDataProvider */
    private SubscriptionPlanDataProvider $subscriptionPlanDataProvider;

    public function __construct(SubscriptionPlanDataProvider $subscriptionPlanDataProvider)
    {
        $this->subscriptionPlanDataProvider = $subscriptionPlanDataProvider;
    }

    public function create($data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function get($id)
    {
        return parent::get($id); // TODO: Change the autogenerated stub
    }

    public function getList()
    {
        $subscriptionPlans = $this->subscriptionPlanDataProvider->findListForAdmin();
        $response = [
            'success' => true,
            'result' => ['subscriptionPlans' => $subscriptionPlans],
        ];

        return new JsonModel($response);
    }
}