<?php

namespace RestAPI\Controller;

use Storytale\CustomerActivity\Application\Query\Subscription\SubscriptionDataProvider;
use Zend\Mvc\Controller\AbstractRestfulController;

class SubscriptionController extends AbstractRestfulController
{
    /** @var SubscriptionDataProvider */
    private SubscriptionDataProvider $subscriptionDataProvider;

    public function __construct(SubscriptionDataProvider $subscriptionDataProvider)
    {
        $this->subscriptionDataProvider = $subscriptionDataProvider;
    }

    public function create($data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function getList()
    {
        return parent::getList(); // TODO: Change the autogenerated stub
    }

    public function get($id)
    {
        return parent::get($id); // TODO: Change the autogenerated stub
    }
}